name: "Build and Push UI Docker Image to ACR"
on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
  
permissions:
  id-token: write
  contents: read
  
jobs:
  build-and-push:
    name: build-and-push
    runs-on: ubuntu-latest
    
    env:
      ACR_NAME: lucktodoappacr2025                        # 👈 your actual ACR name
      IMAGE_NAME: microtodoui                             # 👈 image name
      IMAGE_TAG: v1                                       # 👈 image tagging
      RESOURCE_GROUP: dev-todoapp-rglav                   # 👈 same RG where ACR is
      LOCATION: Central India                             # 👈 your ACR region
      ACR_LOGIN_SERVER: lucktodoappacr2025.azurecr.io
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

        # Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Build React App
      # - name: Build React Application
      #   run: npm run build

      # # Generate Test Coverage
      # - name: Run Test Coverage
      #   run: npm run test:coverage

      # SonarCloud Scan
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # Quality Gate Check
      - name: Sonar Quality Gate Check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # Azure Login
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
    
      # Login to Azure using OIDC
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      - name: Azure CLI - Login to ACR
        run: |
          az acr login --name $ACR_NAME

      # Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          
     # Tag Image to ACR
      - name: Tag Docker Image for ACR
        run: |
          docker tag $IMAGE_NAME:$IMAGE_TAG $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG

      # Push image to ACR
      - name: Push Image to ACR
        run: |
          docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG

      # Optional: Print image name
      - name: Show pushed image name
        run: echo " Image pushed successfully:$ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG"    
